name: DiabloSMP
version: '${project.version}'
main: com.diablosmp.plugin.DiabloPlugin
api-version: 1.20
authors: [ minetwice ]
description: DiabloSMP Core Plugin
commands:
  diablo:
    description: Admin command for DiabloSMP
    permission: diablo.admin
  trust:
    description: Manage player trust contracts
